spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_management_db
    username: postgres
    password: momen


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
